### ISSUE TITLE
Unable to scan localhost 

### ISSUE THREAD

**Issue by eirckr** [stevenvachon/broken-link-checker#207] opened 2020-10-23 14:35 UTC
**Environment:**
 - OS and version: macOS Catalina 10.15.7
 - Node.js version: v10.16.3
 - broken-link-checker version: 0.7.8

I'm not able to scan my localhost. Every time I run a scan it completes right away. If I point to a different site the scan runs but not local. Here is my code. Am I missing something here? 

```
var { SiteChecker } = require("broken-link-checker");
var logCount = 0

const siteChecker = new SiteChecker(
    { 
        excludeInternalLinks: false,
        excludeExternalLinks: false, 
        filterLevel: 0,
        acceptedSchemes: ["http", "https"],
        excludedKeywords: ["other" ],
       
    },
    {
        "error": (error) => {
            console.error(error);
        
        },

        "link": (result, customData) => {
            if(result.broken) {
                if(result.http.response && ![undefined, 200].includes(result.http.response.statusCode)) {
                    console.log(`${result.http.response.statusCode} => ${result.url.original}`);
                }
            }

            console.log("Scanning link:" + logCount);
            logCount++;
            

        },

        "end": () => {
            console.log("COMPLETED!");
        }
    }
);


siteChecker.enqueue("http://localhost:8000/");

```

**Comment by StefanTheWiz** [comment] 2020-11-02 14:47
worked fine for me using node v12.18.4 in docker

**Comment by sators** [comment] 2020-11-12 12:54
Same problem here - duplicate of https://github.com/stevenvachon/broken-link-checker/issues/181

**Closed** 2021-03-04 12:51 UTC
Labels: question
