### ISSUE TITLE
Reports 404 on valid links with non latin characters

### ISSUE THREAD

**Issue by dvdobrovolskiy** [stevenvachon/broken-link-checker#82] opened 2017-08-12 21:38 UTC
For ex
├─BROKEN─ http://allomama.ru/image/cache/data/Kolyaski/Aksessuarji/BUMBLERIDE/Сумка_Parent_Pack_BUMBLERIDE/sumka-bumbleride-parent-pack720088144-170x170.jpg (HTTP_404)

**Comment by stevenvachon** [comment] 2017-08-13 02:48
Duplicate of #64

**Closed by stevenvachon** 2017-08-13 02:48 UTC
