### ISSUE TITLE
Question: CLI Output broken links only?

### ISSUE THREAD

**Issue by JayHoltslander** [stevenvachon/broken-link-checker#200] opened 2020-06-22 22:43 UTC
Currently running on my local machine with:

``blc http://mymac.local:5757/blog -ro --exclude-external > output.txt``

Is there a way I can modify the above command to only output broken links and ignore all "0 broken" links?
I checked ``--help`` to look for an option but didn't see a way to do this.

**Comment by xyzes** [comment] 2020-06-23 05:38
I believe you would need to install the Programmatic API and write a script with your own instance of the broken-link-checker; the command might not be enough to do that since it shows them all by default.

In my script I used the HtmlUrlChecker class, and I modified the 'link' function. You could do something like this and you can further tweak it to check or display how you want it:

```
const htmlUrlChecker = new HtmlUrlChecker(options)
  .on('error', (error) => {})
  .on('html', (tree, robots, response, pageURL, customData) => {})
  .on('queue', () => {})
  .on('junk', (result, customData) => {})
  .on('link', (result, customData) => {
    if (result.broken) {
      console.log(result.brokenReason, result.url.resolved)
    }
  })
  .on('page', (error, pageURL, customData) => {})
  .on('end', () => {});

htmlUrlChecker.enqueue(pageURL, customData);
```

**Comment by xyzes** [comment] 2020-06-23 14:11
Looks like the ability to this via the command line has already been requested!

Duplicate of #133

**Comment by xyzes** [comment] 2020-06-23 14:13
Being able to do this via the command line has already been requested!
#133

**Comment by xyzes** [comment] 2020-06-23 14:37
There is an issue opened for this and it includes a few more solutions & workarounds: #133

**Closed** 2020-06-23 14:41 UTC
Labels: question

**Comment by frederickjh** [comment] 2021-03-26 15:44
And there is a push request #137 that implements this that came out of issue #133, that seems to have been ignored for over two years, as it does not have one comment.
