### ISSUE TITLE
blc at command line is failing

### ISSUE THREAD

**Issue by kselbee** [stevenvachon/broken-link-checker#95] opened 2018-01-19 17:46 UTC
￿MacBook-Pro:~ ME$ blc https://yahoo.com -ro
/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/urlobj/lib/parseUrl.js:124
			if (url.search[0] === "?")
			              ^

TypeError: Cannot read property '0' of null
    at Object.parseUrl [as parse] (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/urlobj/lib/parseUrl.js:124:18)
    at getRobotsTxt (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/lib/internal/getRobotsTxt.js:13:15)
    at item (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/lib/public/SiteChecker.js:43:5)
    at callHandler (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/limited-request-queue/lib/index.js:130:12)
    at startNext (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/limited-request-queue/lib/index.js:265:4)
    at RequestQueue.enqueue (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/limited-request-queue/lib/index.js:64:3)
    at SiteChecker.enqueue (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/lib/public/SiteChecker.js:150:27)
    at run (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/lib/cli.js:505:11)
    at cli.input (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/lib/cli.js:161:3)
    at Object.<anonymous> (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/bin/blc:3:31)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
MEs-MacBook-Pro:~ ME$ blc https://google.com -ro
/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/urlobj/lib/parseUrl.js:124
			if (url.search[0] === "?")
			              ^

TypeError: Cannot read property '0' of null
    at Object.parseUrl [as parse] (/Users/ME/.nvm/versions/node/v9.4.0/lib/node_modules/broken-link-checker/node_modules/urlobj/lib/parseUrl.js:124:18)

**Comment by stevenvachon** [comment] 2018-01-19 17:59
Duplicate of #89

**Closed by stevenvachon** 2018-01-19 17:59 UTC
