### ISSUE TITLE
HTTPS certificate issue - can these be ignored?

### ISSUE THREAD

**Issue by ashewring** [stevenvachon/broken-link-checker#74] opened 2017-05-31 11:58 UTC
I've run across a similar issue to https://github.com/stevenvachon/broken-link-checker/issues/58:

$ blc https://colab.aut.ac.nz/
Getting links from: https://colab.aut.ac.nz/
Error: unable to verify the first certificate

I have to use the -k option for curl to work correctly:

$ curl -ik https://colab.aut.ac.nz/

Without this option, curl reports "(60) SSL certificate problem: unable to get local issuer certificate"
(More details here: http://curl.haxx.se/docs/sslcerts.html)

Could a flag be provided so that this certificate failure can be ignored? Loading the page in the browser works fine, so I would like to mimic that rather than be strict about certificates.

**Comment by stevenvachon** [comment] 2017-05-31 13:37
Are they ignored in the `v0.8.0` branch?:
```shell
npm install stevenvachon/broken-link-checker#v0.8.0
```

**Comment by ashewring** [comment] 2017-05-31 20:40
Yes, 0.8.0 works :) When do you plan to publish it as the "official" blc?

+ blc https://colab.aut.ac.nz
Getting links from: https://colab.aut.ac.nz/
├───OK─── https://twitter.com/CoLab_AUT
├───OK─── https://www.youtube.com/channel/UCDzXVaZkIGY8b95PseHYyOg
├───OK─── https://www.google.co.nz/maps/place/Colab+AUT/@-36.8537071,174.765765,15z/data=!4m5!3m4!1s0x0:0xca4f8ac55285bd1b!8m2!3d-36.8533638!4d174.7658649
├───OK─── https://colab.aut.ac.nz/wp-content/themes/colab2/images/logo.jpg
├───OK─── https://www.facebook.com/AUTCoLab
├───OK─── https://colab.aut.ac.nz/about/
├───OK─── https://colab.aut.ac.nz/courses/
├───OK─── https://colab.aut.ac.nz/events/
├───OK─── https://colab.aut.ac.nz/research/
├───OK─── https://colab.aut.ac.nz/labs/
├───OK─── https://colab.aut.ac.nz/calls/
├───OK─── https://colab.aut.ac.nz/collaborations/
├───OK─── https://colab.aut.ac.nz/publications/
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Arda.gif
├───OK─── https://colab.aut.ac.nz/events/may-creative-technologists-meetup-performance-lab/
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/01/Colab_BCT_2016_Showcase_MCA-41-674x300.jpg
├───OK─── https://colab.aut.ac.nz/events/colab-open-studio-2017/
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2015/03/Bio_Antonin.bmp
├───OK─── https://colab.aut.ac.nz/collaborations/ataata/
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/05/Charged-e1496015075354-674x300.jpg
├───OK─── https://colab.aut.ac.nz/collaborations/antipodes-futur-en-seine-2017/
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/01/Blacklight_20170119_141612-674x300.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/01/Blacklight_20170119_141612-160x160.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Courses-160x160.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Courses-400x400.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Courses-768x768.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Courses-624x624.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Courses.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Events-160x160.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Events-400x400.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Events-768x768.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Events-624x624.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2017/04/Events.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Research-160x160.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Research-400x400.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Research-768x768.jpg
├───OK─── https://colab.aut.ac.nz/wp-content/uploads/2013/05/Research-624x624.jpg

**Comment by stevenvachon** [comment] 2017-06-02 17:14
Soon, I hope.

**Comment by stevenvachon** [comment] 2017-11-08 14:52
I think this is a duplicate of #42. Closing.

**Closed by stevenvachon** 2017-11-08 14:52 UTC
Labels: enhancement
