### ISSUE TITLE
Error: Unhandled Rejection. Error: self signed certificate

### ISSUE THREAD

**Issue by nar3nd3r** [stevenvachon/broken-link-checker#77] opened 2017-07-19 06:40 UTC
Well, does it not accept self signed certificates.

narender@macBook:[broken-link-checker] blc https://bcv-10324:8443/smu/help/docinfo.html -ro --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0"  --filter-level 2 -v | tee ~/Downloads/log.txt
Error: Unhandled Rejection. Error: self signed certificate
narender@macBook:[broken-link-checker]

**Comment by stevenvachon** [comment] 2017-07-19 13:58
Well, duplicate of #42

**Closed by stevenvachon** 2017-07-19 13:58 UTC
